CREATE SCHEMA IF NOT EXISTS GITHUB_RAW
OPTIONS (location = 'US');

CREATE SCHEMA IF NOT EXISTS GITHUB_STAGING
OPTIONS (location = 'US');

CREATE SCHEMA IF NOT EXISTS GITHUB_ANALYTICS
OPTIONS (location = 'US');