name: 'de-project-end-to-end'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  de-project-end-to-end:
    staging:
      +schema: GITHUB_STAGING
      +materialized: view
    marts:
      +schema: GITHUB_ANALYTICS
      +materialized: table