default:
  outputs:
    default:
      type: bigquery
      method: service-account
      project: github-analytics-501910
      dataset: github_staging
      keyfile: "{{ env_var('GCP_KEYFILE') }}"
      threads: 6
  target: default